version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - mydb:/var/lib/postgresql/data

  next-app:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:admin@postgres:5432/mydb?search_path=public
    ports:
      - 3000:3000
    networks:
      - my-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

networks:
  my-network:

volumes:
  mydb:
